### ISSUE TITLE
Request: spicetify-cli

### ISSUE THREAD

**Issue by timescam** [chaotic-aur/infra#100]
aur: https://aur.archlinux.org/packages/spicetify-cli/

**Comment by PedroHLC** [comment]
It's built, please let me know if it doesn't work as expected.
Otherwise, feel free to close this issue!

_____ THANKS FOR THE ONE HUNDRED ISSUE! ______

**Comment by timescam** [comment]
Tested, working as intended

Thank you for maintaining this awesome repo
