### ISSUE TITLE
Git/Bzr packages which "replace" their stable counterparts

### ISSUE THREAD

**Issue by kode54** [chaotic-aur/infra#103]
There are at least two packages which chaotic-aur builds, which are Git/Bzr or other source tip packages, which declare themselves to be replacements for their stable counterparts, and therefore always cause package management to offer them as replacements on every system update pass.

Thus far, the following two have been reported:

`kdisplay-git` - `replaces: kscreen`
`libappindicator-bzr` - `replaces: libappindicator-gtk3`

There may be other such packages in the repository, it may be worth sweeping all the PKGBUILDs for `replaces` declarations, and listing them here.

Worth telling these packages' maintainers, too, since this declaration really only becomes a problem if anyone is building to custom repositories and doesn't want the bleeding edge replacements.

**Comment by PedroHLC** [comment]
Good news, Valmar33 already fixed `kdisplay-git`.

**Comment by PedroHLC** [comment]
Please move this issue to [new infra repo](https://github.com/chaotic-aur/packages).
