### ISSUE TITLE
Matrix.org qt clients

### ISSUE THREAD

**Issue by fabianski7** [chaotic-aur/infra#104]
`quaternion`, `quaternion-git`	

`spectral-matrix`, `spectral-matrix-git`

`nheko`, `nheko-git`

`matrix-mirage`, `matrix-mirage-git`

**Comment by PedroHLC** [comment]
Should all be there, except `spectral-matrix`, that didn't build.
Please let me know if everything works, and if it does, feel free to close this issue!

Thanks for your contribution.

**Comment by fabianski7** [comment]
Thank you.

Seems like the broken build from the package `spectral-matrix` [is a know bug](https://gitlab.com/spectral-im/spectral/-/issues/207).
I will keep this issue active until the bug is fixed, is it okay for you?

**Comment by PedroHLC** [comment]
That's a good ideia

**Comment by PedroHLC** [comment]
Please move this issue to [new infra repo](https://github.com/chaotic-aur/packages.
