### ISSUE TITLE
 Reasonable [request]

### ISSUE THREAD

**Issue by Galcian79** [chaotic-aur/infra#88]
It would be possible to take kernels major updates on hold until nvidia-dkms packages get properly patched?
I become really sad when my system falls apart :(

**Comment by PedroHLC** [comment]
Actually I just noticed you asked for `nvidia-dkms`.

Nope, I won't wait, we have our own NVIDIA (`chaotic-nvidia-tkg{,-dev}`) just for that.

{ NVIDIA, Linux, GCC } This trio have to always be in sync, and I already can't manipulate Linux and GCC.

Next time, I'll wait `chaotic-nvidia-dkms` to be ready (this time it was broken for almost 12h).

**Comment by PedroHLC** [comment]
I'll be adding a note to index.html, so people will know that chaotic-nvidia supports all kernels in repo.

**Comment by PedroHLC** [comment]
I've added the note.

Thanks for your contribution!

**Comment by Galcian79** [comment]
> Actually I just noticed you asked for `nvidia-dkms`.
> 
> Nope, I won't wait, we have our own NVIDIA (`chaotic-nvidia-tkg{,-dev}-dkms`) just for that.
> 
> { NVIDIA, Linux, GCC } This trio have to always be in sync, and I already can't manipulate Linux and GCC.
> 
> Next time, I'll wait `chaotic-nvidia-dkms` to be ready (this time it was broken for almost 12h).

Chaotic-nvidia-dkms i mispelled sorry

**Comment by PedroHLC** [comment]
Then don't worry :smile:  they'll be updated in the correct order with Linux 5.8 (if we survive 2020)
