### ISSUE TITLE
linux-tkg MuQSS option should work again, but I advise not enabling it

### ISSUE THREAD

**Issue by kode54** [chaotic-aur/infra#92]
I was just using my own MuQSS build, now that the latest patch set is available for the 5.7 kernel. Both my SO and I were running the zen version, with the only differences being commandline (mine empty, his equipped with a bunch of mitigation disables and an EDID override for a cheap TV that his video defaults to 1366x768 instead of its native 1920x1080 for some reason), our CPUs. (I have a Ryzen 7 2700, he has a 2400G), and our video hardware. (I have an RX 480 8GB, he has the 2400G's Vega iGPU)

Both within an hour of each other, our systems froze on us, his while we were playing Minecraft, and mine while I was compiling in Visual Studio inside a Windows 10 VM.

I can only blame the scheduler choice, and not our hardware or the base kernel itself.

He went back to Windows 10, blowing that install away, while I reverted to the Arch stable kernel I keep installed for backup, and then later installed linux-tkg-pds-zen from your repository, and have been plugging along fine since.

Relevant to continuing use of MuQSS, though. You should be setting the _timer_freq to 100 for that scheduler, as that's the optimal choice for MuQSS. You're welcome to test that kernel on whatever you have handy, but I'd be careful. (Re: 100Hz, the PKGBUILD in linux-tkg for a while didn't accept that as a configuration setting and required manually setting it at the prompt when running makepkg)

**Comment by PedroHLC** [comment]
:thinking:  It would be good to open an issue on @Tk-Glitch's linux repo about this system freeze.
If it's broken I cannot add it back.

**Comment by PedroHLC** [comment]
Early in the morning I've wiped the old ones and put the new version to build with 100Hz, let me know if this last version is more stable.

**Comment by kode54** [comment]
Tested. It runs fine, until I try to put my machine to sleep. Sleeping never manages to achieve sleep state, just powers off my screens and leaves the system dead to the world. Sleeps fine on the Arch kernel. I'll test sleep on your recently updated PDS kernel again later.

**Comment by Fzndox** [comment]
> Tested. It runs fine, until I try to put my machine to sleep. Sleeping never manages to achieve sleep state, just powers off my screens and leaves the system dead to the world. Sleeps fine on the Arch kernel. I'll test sleep on your recently updated PDS kernel again later.

Since the latest version (the past few days) I'm also unable to sleep, with the exact same problem.

**Comment by PedroHLC** [comment]
Moving this discussion to #98
