### ISSUE TITLE
PCSX2-git crashes: "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by ViNi-Arco** [chaotic-aur/infra#93]
Hello dear, I am having this `Illegal instruction (core dumped)` problem when running PCSX2 git, and I found this:
https://bugs.archlinux.org/task/43796

This problem was solved in the Arch repositories, you can check, because in the PCSX2 of the Arch repository it is running correctly, thanks for the attention

**Comment by PedroHLC** [comment]
I've made the same change that was commit in the update alucryd refers in this Bugzilla.
That is: `-DDISABLE_ADVANCE_SIMD='TRUE'`

If this works, let the maintainer now in AUR https://aur.archlinux.org/packages/pcsx2-git
Please, let me know too.

**Comment by ViNi-Arco** [comment]
Thank you very much Pedro, it's working now, have a good day
https://img.tpx.cz/uploads/pcsx2fixed.png

**Comment by ViNi-Arco** [comment]
Hi Pedro, I already reported the problem with the solution at AUR :thumbsup:

**Comment by PedroHLC** [comment]
That is great, thanks :blush:
