### ISSUE TITLE
Add VKD3D Fork Edition

### ISSUE THREAD

**Issue by IroAlexis** [chaotic-aur/infra#94]
Hello all,

Can you add `vkd3d-fork` (`lib32-vkd3d-fork`) please ? As requested in the "recent" changes (https://github.com/Frogging-Family/vkd3d-git/commit/3649f6cdcd45e4407a2853eb619ab7d6bb676650) from using VKD3D with Wine TkG.

I build my proper Wine package and I would like use this VKD3D version (specialy for the futur with https://github.com/HansKristian-Work/vkd3d/tree/khr-raytracing).

Thanks for all
Love you

**Comment by PedroHLC** [comment]
I totally forgot to say, I've added `{lib32-,}vkd3d-tkg-git`.

Please let me know if it works and fulfill your needs. If it does, feel free to close this issue.

**Comment by IroAlexis** [comment]
I'll test that tonight ! Nice thank you for your job 💯

**Comment by IroAlexis** [comment]
It's perfect ! I don't have an "error" when I build my Wine package (with `_use_vkd3d="fork"`). Actually, I can close the issue !
Thank you for honoring my request
