### ISSUE TITLE
linux-tkg-* packages are outdated

### ISSUE THREAD

**Issue by emanuelserpa** [chaotic-aur/infra#97]
repo is 5.7.4 and "upstream" is on 5.7.6

**Comment by PedroHLC** [comment]
Thanks for letting me know, the build was blocked because of a weird prompt and has now being resumed.

**Comment by emanuelserpa** [comment]
@PedroHLC linux-tkg-bmq-*, linux-tkg-pds-* are still outdated.

**Comment by PedroHLC** [comment]
They're all 5.7.6
![image](https://user-images.githubusercontent.com/1368952/85950084-ef257680-b930-11ea-8ae6-49b6f29a1846.png)

**Comment by emanuelserpa** [comment]
Sorry. My bad.
