### ISSUE TITLE
linux-tkg-muqss: Unable to sleep

### ISSUE THREAD

**Issue by Fzndox** [chaotic-aur/infra#98]
Sleeping never manages to achieve sleep state, just powers off screens, disables network but leaves the system powered on. 
Sleeps fine on the Arch kernel.

**Comment by PedroHLC** [comment]
Moved from: https://github.com/chaotic-aur/infra/issues/92#issuecomment-651275356

**Comment by PedroHLC** [comment]
@Tk-Glitch maybe you can help on this one? :frog:

**Comment by kode54** [comment]
Yes, they're tracking the issue:

https://github.com/Frogging-Family/linux-tkg/issues/24

**Comment by Tk-Glitch** [comment]
> Sleeps fine on the Arch kernel
Is it the exact same version though? People have been encountering the issue on stock kernel, be it on Arch or other distros.

**Comment by kode54** [comment]
My machine sleeps fine on the Arch kernel, version 5.7.6-1.

**Comment by PedroHLC** [comment]
TkG solved this. Fix will be available with the `5.7.6-14` builds.

**Comment by Fzndox** [comment]
Confirmed fixed under 5.7.6-14.
